-- 1.

CREATE TABLE USER_TEST(
	ID NUMBER(1),
	Name VARCHAR2(30),
	ReserveDate DATE,
	RoomNum NUMBER(4)
);

DROP TABLE USER_TEST;

INSERT INTO USER_TEST
VALUES(1, '홍길동', '2016/01/05', 2014);

INSERT INTO USER_TEST
VALUES(2, '임꺽정', '2016/02/12', 918);

INSERT INTO USER_TEST
VALUES(3, '장길산', '2016/01/16', 1208);

INSERT INTO USER_TEST
VALUES(4, '홍길동', '2016/03/17', 504);

INSERT INTO USER_TEST
VALUES(6, '김유신', NULL, NULL);

SELECT *
FROM USER_TEST;

-----------------------------------------------
-- 2.
UPDATE USER_TEST SET
ROOMNUM = 2002
WHERE ID = 1 OR ID = 4;

DELETE FROM USER_TEST
WHERE NAME = '김유신';

----------------------------------------------
-- 3.
UPDATE USER_TEST SET
ROOMNUM = 2002;

SELECT *
FROM USER_TEST;

-------------------------------------------------------------
-- 4.
CREATE TABLE EMPLOYEE4 AS SELECT * FROM EMPLOYEE;

SELECT *
FROM EMPLOYEE4;

-------------------------------------------------------------------
-- 5.
UPDATE EMPLOYEE4 SET
SALARY = SALARY + 1000000
WHERE HIRE_DATE < '2000/01/01';

SELECT *
FROM EMPLOYEE4;

------------------------------------------------------------------
-- 6.
SELECT EMP_NAME
FROM EMPLOYEE4
JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
WHERE NATIONAL_CODE = 'KO';

UPDATE EMPLOYEE4 SET
BONUS = 0.5
WHERE EMP_NAME IN(SELECT EMP_NAME
FROM EMPLOYEE4
JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
WHERE NATIONAL_CODE = 'KO');

SELECT EMP_NAME 
FROM EMPLOYEE4
WHERE BONUS = 0.5;









